name: Deploy to yunohost
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.ARTIFACT_PORT }} ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass python3 python3-pip

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.ARTIFACT_HOST }}
            username: ${{ secrets.USER }}
            port: ${{ secrets.ARTIFACT_PORT }}
            key: ${{ secrets.ARTIFACT_SSH_KEY }}
            passphrase: ${{ secrets.SSH_PSWD }}
            command_timeout: 5m
            script: ${{ secrets.APP_PATH }}/deploy.sh
